spring:
  application:
    name: jwtReactSpring

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    com:
      zaxxer: INFO
    org:
      springframework:
        security: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug

# jwt secret Key
jwt:
  secret: askldfhaklsdflzxcvgklsadfngsfdnklgvdfklgnlkdf1557fsdfsdfsdfsasdfasdfwefdfdf